language: python

python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE="insurance.settings"
    - PYTHONPATH="/home/travis/build/bayodesegun/insurance-risks-api"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.7

# install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - python manage.py syncdb --noinput

# run the test suite
script:
  - python manage.py test
  